MVC_Proyecto_GRM/Models/ViewModels/Rentas/RentaAgregar.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Xml.Linq;

namespace MVC_Proyecto_GRM.Models.ViewModels.Rentas
{
    public class RentaAgregar
    {
        public int RentaId { get; set; }

        [Required]  // Data validator
        [Display(Name = "Vehiculo")]   // Manda el name de lo que falta
        public int VehiculoId { get; set; }

        [Required]  // Data validator
        [Display(Name = "Cliente")]   // Manda el name de lo que falta
        public int ClienteId { get; set; }

        [Required]  // Data validator
        [Display(Name = "Empleado")]   // Manda el name de lo que falta
        public int EmpleadoId { get; set; }

        [Required]  // Data validator
        [Display(Name = "Costo")]   // Manda el name de lo que falta
        public float Costo { get; set; }

        [Required]  // Data validator
        [Display(Name = "Fecha de Renta")]   // Manda el name de lo que falta
        [DataType(DataType.Date)]
        public DateTime FechaRenta { get; set; }

        [Required]  // Data validator
        [Display(Name = "Fecha de Renta Fin")]   // Manda el name de lo que falta
        [DataType(DataType.Date)]
        public DateTime FechaRentaFin { get; set; }
    }
}

MVC_Proyecto_GRM/Models/ViewModels/Rentas/RentasListar.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC_Proyecto_GRM.Models.ViewModels.Rentas
{
    public class RentasListar
    {
        public int RentaId { get; set; }
        public int VehiculoId { get; set; }
        public string Vehiculo { get; set; }
        public int ClienteId { get; set; }
        public string Cliente { get; set; }
        public int EmpleadoId { get; set; }
        public string Empleado { get; set; }
        public float Costo { get; set; }
        public DateTime FechaRenta { get; set; }
        public DateTime FechaRentaFin { get; set; }
    }
}

MVC_Proyecto_GRM/Controllers/RentasController.cs
using MVC_Proyecto_GRM.Models.ViewModels.Direcciones;
using MVC_Proyecto_GRM.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_Proyecto_GRM.Models.ViewModels.Rentas;
using static MVC_Proyecto_GRM.Models.Enum;
using MVC_Proyecto_GRM.Models.ViewModels.Clientes;
using MVC_Proyecto_GRM.Models.DDLs;

namespace MVC_Proyecto_GRM.Controllers
{
    public class RentasController : Controller
    {
        // GET: Rentas
        public ActionResult Index()
        {
            List<RentasListar> lista = new List<RentasListar>();

            // Entity framework
            using (RentaCarrosEntities db = new RentaCarrosEntities())
            {
                // LinQ
                lista = (from r in db.Rentas
                         join v in db.Vehiculos on r.VehiculoId equals v.VehiculoId
                         join c in db.Clientes on r.ClienteId equals c.ClienteId
                         join e in db.Empleados on r.EmpleadoId equals e.EmpleadoId
                         select new RentasListar
                         {
                             RentaId = r.RentaId,
                             VehiculoId = r.VehiculoId,
                             Vehiculo = "Marca: " + v.Marca + " Modelo: " + v.Modelo + " Matrícula " + v.Matricula,
                             ClienteId = r.ClienteId,
                             Cliente = c.Nombre + " " + c.ApellidoP + " " + c.ApellidoM,
                             EmpleadoId = r.EmpleadoId,
                             Empleado = e.Nombre + " " + e.ApellidoP + " " + e.ApellidoM,
                             Costo = (float)r.Costo,
                             FechaRenta = r.FechaRenta,
                             FechaRentaFin = r.FechaRentaFin
                         }).ToList();
            }

            return View(lista);
        }

        public ActionResult RentaAgregar()
        {
            CargarDDL();
            return View();
        }

        [HttpPost] // Data validator
        public ActionResult RentaAgregar(RentaAgregar model)
        {
            try
            {
                // Validar si modelo es correcto
                if (ModelState.IsValid && model.VehiculoId != 0 && model.ClienteId != 0 && model.EmpleadoId != 0)
                {
                    if (model.FechaRenta < DateTime.Now || model.FechaRentaFin <= model.FechaRenta || model.FechaRentaFin < DateTime.Now)
                    {
                        Alert("La fecha renta debe ser mayor al día actual y fecha renta fin debe ser mayor a fecha renta y al día actual.", NoticationType.warning);
                        CargarDDL();
                        return View(model);
                    }
                    else
                    {
                        using (RentaCarrosEntities db = new RentaCarrosEntities())
                        {
                            var renta = new Rentas();

                            renta.VehiculoId = model.VehiculoId;
                            renta.ClienteId = model.ClienteId;
                            renta.EmpleadoId = model.EmpleadoId;
                            renta.Costo = model.Costo;
                            renta.FechaRenta = model.FechaRenta;
                            renta.FechaRentaFin = model.FechaRentaFin;

                            // Se agrega el nuevo camion
                            db.Rentas.Add(renta);
                            db.SaveChanges();
                            Alert("La Renta ha sido agregada", NoticationType.success);
                        }
                    }
                    // Redirecciona a la lista de camiones (Controller)
                    return Redirect("~/Rentas");
                }
                Alert("Verificar la información", NoticationType.warning);
                CargarDDL();
                return View(model);
            }
            catch (Exception ex)
            {
                Alert("Verificar la información", NoticationType.warning);
                CargarDDL();
                return View(model);
            }
        }

        public ActionResult RentaEditar(int id)
        {
            Rentas renta = new Rentas();

            using (RentaCarrosEntities db = new RentaCarrosEntities())
            {
                //camion = db.Camiones.Where(x => x.CamionId == camionId).OrderBy(x => x.Matricula).FirstOrDefault();
                renta = db.Rentas.Where(x => x.RentaId == id).FirstOrDefault();
                if (renta.FechaRenta > DateTime.Now)
                {
                    //Cambia todo
                    ViewBag.CambiarTodo = 1;
                }
                else if (renta.FechaRentaFin < DateTime.Now)
                {
                    // No cambia nada
                    ViewBag.CambiarTodo = 3;
                }
                else
                {
                    // Cambia solo costo y fecha
                    ViewBag.CambiarTodo = 2;
                }
            }

            CargarDDL();
            return View(renta);
        }

        [HttpPost]
        public ActionResult RentaEditar(Rentas model)
        {
            try
            {
                // Validar si modelo es correcto
                if (ModelState.IsValid)
                {
                    string dateRenta = model.FechaRenta.ToShortDateString();
                    string dateHoy = model.FechaRenta.ToShortDateString();

                    DateTime dateRentaD = DateTime.Parse(dateRenta);
                    DateTime dateRentaH = DateTime.Parse(dateHoy);

                    if (dateRentaD >= dateRentaH && model.FechaRentaFin > model.FechaRenta && model.FechaRentaFin > DateTime.Now)
                    {
                        using (RentaCarrosEntities db = new RentaCarrosEntities())
                        {
                            var renta = new Rentas();

                            renta.RentaId = model.RentaId;
                            renta.VehiculoId = model.VehiculoId;
                            renta.ClienteId = model.ClienteId;
                            renta.EmpleadoId = model.EmpleadoId;
                            renta.Costo = model.Costo;
                            renta.FechaRenta = model.FechaRenta;
                            renta.FechaRentaFin = model.FechaRentaFin;

                            // Se agrega el nuevo camion                        
                            db.Entry(renta).State = System.Data.Entity.EntityState.Modified;
                            db.SaveChanges();

                            Alert("La Renta ha sido actualizada.", NoticationType.success);
                        }
                        // Redirecciona a la lista de camiones
                        return Redirect("~/Rentas");
                    }
                    else
                    {
                        Alert("NO SE PUDO REALIZAR LA ACTUALIZACIÓN. La fecha renta debe ser mayor o igual al día de hoy y la fecha renta fin debe ser mayor a la fecha renta y al día de hoy.", NoticationType.error);
                        CargarDDL();
                        return Redirect("~/Rentas");
                        //return View(model);
                    }
                }
                Alert("NO SE PUDO REALIZAR LA ACTUALIZACIÓN. Verifica los campos.", NoticationType.warning);
                CargarDDL();
                return Redirect("~/Rentas");
                //return View(model);
            }
            catch (Exception ex)
            {
                Alert("NO SE PUDO REALIZAR LA ACTUALIZACIÓN. Verificar la información", NoticationType.warning);
                CargarDDL();
                return Redirect("~/Rentas");
                //return View(model);
            }
        }

        [HttpGet]
        public ActionResult RentaEliminar(int id)
        {
            Rentas renta = new Rentas();
            try
            {
                using (RentaCarrosEntities db = new RentaCarrosEntities())
                {
                    renta = db.Rentas.Where(x => x.RentaId == id).FirstOrDefault();

                    if (renta.FechaRenta > DateTime.Now)
                    {
                        db.Rentas.Remove(renta);
                        db.SaveChanges();
                        Alert("Renta Eliminada con éxito.", NoticationType.success);
                        return Redirect("~/Rentas");
                    }
                    else
                    {
                        Alert("No se puede eliminar la renta porque la fecha ya paso de la fecha actual.", NoticationType.error);
                        return Redirect("~/Rentas");
                    }
                }

            }
            catch (Exception ex)
            {
                Alert("Error: " + ex.Message, NoticationType.error);
                return Redirect("~/Rentas");
            }
        }

        public void Alert(string message, NoticationType noticationType)
        {
            var msg = "<script language='javascript'>Swal.fire('" + noticationType.ToString().ToUpper() + "', '" + message +
                "','" + noticationType + "')" + "</script>";

            TempData["notification"] = msg;
        }

        public void CargarDDL()
        {
            List<VehiculosDDL> listaV = new List<VehiculosDDL>();
            listaV.Insert(0, new VehiculosDDL { VehiculoId = 0, Info = "Seleccione un vehículo." });

            List<ClientesDDL> listaC = new List<ClientesDDL>();
            listaC.Insert(0, new ClientesDDL { ClienteId = 0, Nombre = "Seleccione un cliente." });

            List<EmpleadosDDL> listaE = new List<EmpleadosDDL>();
            listaE.Insert(0, new EmpleadosDDL { EmpleadoId = 0, Nombre = "Seleccione un empleado." });

            using (RentaCarrosEntities db = new RentaCarrosEntities())
            {
                foreach (var v in db.Vehiculos)
                {

MVC_Proyecto_GRM/Views/Rentas/Index.cshtml
@model List<MVC_Proyecto_GRM.Models.ViewModels.Rentas.RentasListar>
@{
    ViewBag.Title = "Listar de Rentas";
}

<div class="row p-md-2">
    <div class="card text-bg-dark">
        <img src="/Recursos/wp-1.jpg" class="card-img" alt="...">
        <div class="card-img-overlay text-center">
            <h1 class="card-title">@ViewBag.Title</h1>
            <p class="card-text">
                <small>
                    Para recordar como se manejan las acciones clic
                    @Html.ActionLink("aquí", "About", "Home", new { area = "" }, new { @class = "text-primary" }).
                </small>
            </p>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-2 m-md-2" style="text-align: right;">
        <a href="~/Rentas/RentaAgregar" class="btn btn-primary">Agregar Renta</a>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-striped table-bordered">

            <tr class="bg-warning text-center">
                <th style="width: 15%;">ID Renta</th>
                <th>Vehículo</th>
                <th>Cliente</th>
                <th>Empleado</th>
                <th>Costo</th>
                <th>Fecha de Renta</th>
                <th>Fecha de Renta Fin</th>
                <th>Acciones</th>
            </tr>

            @foreach (var Elemento in Model)
            {
                <tr class="text-center">
                    <td>@Elemento.RentaId</td>
                    <td>@Elemento.Vehiculo</td>
                    <td>@Elemento.Cliente</td>
                    <td>@Elemento.Empleado</td>
                    <td>@Elemento.Costo</td>
                    <td>@Elemento.FechaRenta</td>
                    <td>@Elemento.FechaRentaFin</td>
                    <td>
                        <a class="btn btn-warning" href="~/Rentas/RentaEditar/@Elemento.RentaId"><i class="fa-solid fa-pen-to-square"></i></a>
                        <a class="btn btn-danger" href="~/Rentas/RentaEliminar/@Elemento.RentaId"><i class="fa-solid fa-trash"></i></a>
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

MVC_Proyecto_GRM/Views/Rentas/RentaAgregar.cshtml
@model MVC_Proyecto_GRM.Models.ViewModels.Rentas.RentaAgregar
@{
    ViewBag.Title = "Agregar una nueva renta";
}

<div class="row p-md-2">
    <div class="card text-bg-dark">
        <img src="/Recursos/wp-1.jpg" class="card-img" alt="...">
        <div class="card-img-overlay text-center">
            <h1 class="card-title">@ViewBag.Title</h1>
        </div>
    </div>
</div>

@using (Html.BeginForm("RentaAgregar", "Rentas", FormMethod.Post))    // Metodo, Controller, Post Method
{
    <div class="row">
        <div class="col-md-6">            
            <div>
                @Html.Label("Vehículo", null, new { @class = "lblTitulo" })
                @Html.DropDownListFor(d => d.VehiculoId, new SelectList(ViewBag.ListaVehiculos, "VehiculoId", "Info"), new { @class = "form-control" })
            </div>
            <div>
                @Html.Label("Cliente", null, new { @class = "lblTitulo" })
                @Html.DropDownListFor(d => d.ClienteId, new SelectList(ViewBag.ListaClientes, "ClienteId", "Nombre"), new { @class = "form-control" })
            </div>
            <div>
                @Html.Label("Empleado", null, new { @class = "lblTitulo" })
                @Html.DropDownListFor(d => d.EmpleadoId, new SelectList(ViewBag.ListaEmpleados, "EmpleadoId", "Nombre"), new { @class = "form-control" })
            </div>            
        </div>

        <div class="col-md-6">
            <div>
                @Html.LabelFor(d => d.Costo, null, new { @class = "lblTitulo" })
                @Html.TextBoxFor(d => d.Costo, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Costo, "", new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.FechaRenta, null, new { @class = "lblTitulo" })<br />
                @Html.EditorFor(d => d.FechaRenta, "", new { @class = "date" })
                @Html.ValidationMessageFor(d => d.FechaRenta, "", new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.FechaRentaFin, null, new { @class = "lblTitulo" })<br />
                @Html.EditorFor(d => d.FechaRentaFin, "", new { @class = "date" })
                @Html.ValidationMessageFor(d => d.FechaRentaFin, "", new { @class = "red" })
            </div>
            <div style="text-align: right;">
                <input value="Guardar" class="btn btn-success" type="submit" />
            </div>
        </div>
    </div>
}

MVC_Proyecto_GRM/Views/Rentas/RentaEditar.cshtml
@model MVC_Proyecto_GRM.Models.Rentas

<div class="row p-md-2">
    <div class="card text-bg-dark">
        <img src="/Recursos/wp-1.jpg" class="card-img" alt="...">
        <div class="card-img-overlay text-center">
            <h2 class="card-title">Editando Renta</h2>
            <h4 class="card-body">>>> ID: @Html.ValueFor(d => d.RentaId) <<<</h4>
        </div>
    </div>
</div>

@using (Html.BeginForm("RentaEditar", "Rentas", FormMethod.Post))    // Metodo, Controller, Post Method
{
    <div class="row">
        @if (ViewBag.CambiarTodo == 1)
        {
            <div class="col-md-6">
                @Html.HiddenFor(d => d.RentaId)
                <div>
                    @Html.Label("Vehículo", null, new { @class = "lblTitulo" })
                    @Html.DropDownListFor(d => d.VehiculoId, new SelectList(ViewBag.ListaVehiculos, "VehiculoId", "Info"), new { @class = "form-control" })
                </div>
                <div>
                    @Html.Label("Cliente", null, new { @class = "lblTitulo" })
                    @Html.DropDownListFor(d => d.ClienteId, new SelectList(ViewBag.ListaClientes, "ClienteId", "Nombre"), new { @class = "form-control" })
                </div>
                <div>
                    @Html.Label("Empleado", null, new { @class = "lblTitulo" })
                    @Html.DropDownListFor(d => d.EmpleadoId, new SelectList(ViewBag.ListaEmpleados, "EmpleadoId", "Nombre"), new { @class = "form-control" })
                </div>
            </div>
            <div class="col-md-6">
                <div>
                    @Html.LabelFor(d => d.Costo, null, new { @class = "lblTitulo" })
                    @Html.TextBoxFor(d => d.Costo, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(d => d.Costo, "", new { @class = "red" })
                </div>
                <div>
                    @Html.LabelFor(d => d.FechaRenta, null, new { @class = "lblTitulo" })<br />
                    @Html.EditorFor(d => d.FechaRenta, "", new { @class = "date" })
                    @Html.ValidationMessageFor(d => d.FechaRenta, "", new { @class = "red" })
                </div>
                <div>
                    @Html.LabelFor(d => d.FechaRentaFin, null, new { @class = "lblTitulo" })<br />
                    @Html.EditorFor(d => d.FechaRentaFin, "", new { @class = "date" })
                    @Html.ValidationMessageFor(d => d.FechaRentaFin, "", new { @class = "red" })
                </div>
                <div style="text-align: right;">
                    <input value="Guardar" class="btn btn-success" type="submit" />
                </div>
            </div>
        }
        else if (ViewBag.CambiarTodo == 2)
        {
            <div class="col-md-6">
                @Html.HiddenFor(d => d.RentaId)
                @Html.HiddenFor(d => d.VehiculoId)
                @Html.HiddenFor(d => d.ClienteId)
                @Html.HiddenFor(d => d.EmpleadoId)
                <div>
                    @Html.Label("Vehículo", null, new { @class = "lblTitulo" })
                    @Html.DropDownListFor(d => d.VehiculoId, new SelectList(ViewBag.ListaVehiculos, "VehiculoId", "Info"), new { @class = "form-control", @disabled = "disabled" })
                </div>
                <div>
                    @Html.Label("Cliente", null, new { @class = "lblTitulo" })
                    @Html.DropDownListFor(d => d.ClienteId, new SelectList(ViewBag.ListaClientes, "ClienteId", "Nombre"), new { @class = "form-control", @disabled = "disabled" })
                </div>
                <div>
                    @Html.Label("Empleado", null, new { @class = "lblTitulo" })
                    @Html.DropDownListFor(d => d.EmpleadoId, new SelectList(ViewBag.ListaEmpleados, "EmpleadoId", "Nombre"), new { @class = "form-control", @disabled = "disabled" })
                </div>
            </div>
            <div class="col-md-6">
                <div>
                    @Html.LabelFor(d => d.Costo, null, new { @class = "lblTitulo" })
                    @Html.TextBoxFor(d => d.Costo, "", new { @class = "form-control" })
                    @Html.ValidationMessageFor(d => d.Costo, "", new { @class = "red" })
                </div>
                <div>
                    @Html.LabelFor(d => d.FechaRenta, null, new { @class = "lblTitulo" })<br />
                    @Html.EditorFor(d => d.FechaRenta, "", new { @class = "date", htmlAttributes = new { ReadOnly = true, style = "background-color: #EEEEEE" } })
                    @Html.ValidationMessageFor(d => d.FechaRenta, "", new { @class = "red" })
                </div>
                <div>
                    @Html.LabelFor(d => d.FechaRentaFin, null, new { @class = "lblTitulo" })<br />
                    @Html.EditorFor(d => d.FechaRentaFin, "", new { @class = "date" })
                    @Html.ValidationMessageFor(d => d.FechaRentaFin, "", new { @class = "red" })
                </div>
                <div style="text-align: right;">
                    <input value="Guardar" class="btn btn-success" type="submit" />
                </div>
            </div>
        }
        else if (ViewBag.CambiarTodo == 3)
        {
            <div class="col-md-6">
                @Html.HiddenFor(d => d.RentaId)
                <div>
                    @Html.Label("Vehículo", null, new { @class = "lblTitulo" })
                    @Html.DropDownListFor(d => d.VehiculoId, new SelectList(ViewBag.ListaVehiculos, "VehiculoId", "Info"), new { @class = "form-control", @disabled = "disabled" })
                </div>
                <div>
                    @Html.Label("Cliente", null, new { @class = "lblTitulo" })
                    @Html.DropDownListFor(d => d.ClienteId, new SelectList(ViewBag.ListaClientes, "ClienteId", "Nombre"), new { @class = "form-control", @disabled = "disabled" })
                </div>
                <div>
                    @Html.Label("Empleado", null, new { @class = "lblTitulo" })
                    @Html.DropDownListFor(d => d.EmpleadoId, new SelectList(ViewBag.ListaEmpleados, "EmpleadoId", "Nombre"), new { @class = "form-control", @disabled = "disabled" })
                </div>
            </div>
            <div class="col-md-6">
                <div>
                    @Html.LabelFor(d => d.Costo, null, new { @class = "lblTitulo" })
                    @Html.TextBoxFor(d => d.Costo, "", new { @class = "form-control", @readonly = "readonly" })
                    @Html.ValidationMessageFor(d => d.Costo, "", new { @class = "red" })
                </div>
                <div>
                    @Html.LabelFor(d => d.FechaRenta, null, new { @class = "lblTitulo" })<br />
                    @Html.EditorFor(d => d.FechaRenta, "", new { @class = "date", htmlAttributes = new { ReadOnly = true, style = "background-color: #EEEEEE" } })
                    @Html.ValidationMessageFor(d => d.FechaRenta, "", new { @class = "red" })
                </div>
                <div>
                    @Html.LabelFor(d => d.FechaRentaFin, null, new { @class = "lblTitulo" })<br />
                    @Html.EditorFor(d => d.FechaRentaFin, "", new { @class = "date", htmlAttributes = new { ReadOnly = true, style = "background-color: #EEEEEE" } })
                    @Html.ValidationMessageFor(d => d.FechaRentaFin, "", new { @class = "red" })
                </div>
                <div style="text-align: right;">
                    <input value="Guardar" class="btn btn-success" type="submit" disabled="disabled" />
                </div>
            </div>
        }
    </div>
}