MVC_Proyecto_GRM/Models/ViewModels/Mantenimientos/MantenimientoAgregar.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Xml.Linq;

namespace MVC_Proyecto_GRM.Models.ViewModels.Mantenimientos
{
    public class MantenimientoAgregar
    {
        public int MantenimientoId { get; set; }

        [Required]  // Data validator
        [Display(Name = "ID Vehículo")]   // Manda el name de lo que falta
        public int VehiculoId { get; set; }

        [Required]  // Data validator
        [Display(Name = "Nota")]   // Manda el name de lo que falta
        public string Nota { get; set; }

        [Required]  // Data validator
        [Display(Name = "Fecha")]   // Manda el name de lo que falta
        [DataType(DataType.Date)]
        public DateTime Fecha { get; set; }
    }
}

MVC_Proyecto_GRM/Models/ViewModels/Mantenimientos/MantenimientosListar.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Xml.Linq;

namespace MVC_Proyecto_GRM.Models.ViewModels.Mantenimientos
{
    public class MantenimientosListar
    {
        public int MantenimientoId { get; set; }        
        public int VehiculoId { get; set; }
        public string Vehiculo { get; set; }
        public string Nota { get; set; }        
        public DateTime Fecha { get; set; }
    }
}

MVC_Proyecto_GRM/Controllers/MantenimientosController.cs
using MVC_Proyecto_GRM.Models.ViewModels.Direcciones;
using MVC_Proyecto_GRM.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_Proyecto_GRM.Models.ViewModels.Mantenimientos;
using static MVC_Proyecto_GRM.Models.Enum;
using MVC_Proyecto_GRM.Models.ViewModels.Clientes;
using MVC_Proyecto_GRM.Models.DDLs;

namespace MVC_Proyecto_GRM.Controllers
{
    public class MantenimientosController : Controller
    {
        // GET: Mantenimientos
        public ActionResult Index()
        {
            List<MantenimientosListar> lista = new List<MantenimientosListar>();

            // Entity framework
            using (RentaCarrosEntities db = new RentaCarrosEntities())
            {
                // LinQ
                lista = (from c in db.Mantenimientos
                         join ve in db.Vehiculos on c.VehiculoId equals ve.VehiculoId
                         select new MantenimientosListar
                         {
                             MantenimientoId = c.MantenimientoId,
                             VehiculoId = c.VehiculoId,
                             Vehiculo = "Marca: " + ve.Marca + " Modelo: " + ve.Modelo + " Matrícula: " + ve.Matricula,
                             Nota = c.Nota,
                             Fecha = c.Fecha,
                         }).ToList();
            }

            return View(lista);
        }

        public ActionResult MantenimientoAgregar()
        {
            CargarDDL();

            return View();
        }

        [HttpPost] // Data validator
        public ActionResult MantenimientoAgregar(MantenimientoAgregar model)
        {
            try
            {
                // Validar si modelo es correcto
                if (ModelState.IsValid && model.VehiculoId != 0 && model.Nota != "" && (model.Fecha).ToString() != "")
                {
                    using (RentaCarrosEntities db = new RentaCarrosEntities())
                    {
                        var manteni = new Mantenimientos();

                        manteni.VehiculoId = model.VehiculoId;
                        manteni.Nota = model.Nota;
                        manteni.Fecha = model.Fecha;

                        // Se agrega el nuevo camion
                        db.Mantenimientos.Add(manteni);
                        db.SaveChanges();
                        Alert("El Mantenimiento ha sido agregado", NoticationType.success);
                    }
                    // Redirecciona a la lista de camiones (Controller)
                    return Redirect("~/Mantenimientos");
                }
                Alert("No pueden quedar vacíos los campos.", NoticationType.warning);
                CargarDDL();
                return View(model);
            }
            catch (Exception ex)
            {
                Alert("Error: " + ex.Message, NoticationType.error);
                CargarDDL();
                return View(model);
            }
        }

        public ActionResult MantenimientoEditar(int id)
        {
            Mantenimientos mantenimiento = new Mantenimientos();
            CargarDDL();

            using (RentaCarrosEntities db = new RentaCarrosEntities())
            {
                //camion = db.Camiones.Where(x => x.CamionId == camionId).OrderBy(x => x.Matricula).FirstOrDefault();
                mantenimiento = db.Mantenimientos.Where(x => x.MantenimientoId == id).FirstOrDefault();
            }

            return View(mantenimiento);
        }

        [HttpPost]
        public ActionResult MantenimientoEditar(Mantenimientos model)
        {
            try
            {
                // Validar si modelo es correcto
                if (ModelState.IsValid && model.Nota != "")
                {
                    using (RentaCarrosEntities db = new RentaCarrosEntities())
                    {
                        var mantenimiento = new Mantenimientos();

                        mantenimiento.MantenimientoId = model.MantenimientoId;
                        mantenimiento.VehiculoId = model.VehiculoId;
                        mantenimiento.Nota = model.Nota;
                        mantenimiento.Fecha = model.Fecha;

                        // Se agrega el nuevo camion                        
                        db.Entry(mantenimiento).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();

                        Alert("El Mantenimiento ha sido agregado", NoticationType.success);
                    }
                    // Redirecciona a la lista de camiones
                    return Redirect("~/Mantenimientos");
                }
                Alert("No pueden quedar vacíos los campos.", NoticationType.warning);
                CargarDDL();
                return View(model);
            }
            catch (Exception ex)
            {
                Alert("Error: " + ex.Message, NoticationType.error);
                CargarDDL();
                return View(model);
                //throw new Exception(ex.Message);
            }
        }

        [HttpGet]
        public ActionResult MantenimientoEliminar(int id)
        {
            Mantenimientos mantenimiento = new Mantenimientos();
            try
            {
                using (RentaCarrosEntities db = new RentaCarrosEntities())
                {
                    mantenimiento = db.Mantenimientos.Where(x => x.MantenimientoId == id).FirstOrDefault();
                    db.Mantenimientos.Remove(mantenimiento);
                    db.SaveChanges();
                }
                Alert("Mantenimiento Eliminado con éxito.", NoticationType.success);
                return Redirect("~/Mantenimientos");
            }
            catch (Exception ex)
            {
                Alert("Error: " + ex.Message, NoticationType.error);
                return Redirect("~/Mantenimientos");
            }
        }

        public void Alert(string message, NoticationType noticationType)
        {
            var msg = "<script language='javascript'>Swal.fire('" + noticationType.ToString().ToUpper() + "', '" + message +
                "','" + noticationType + "')" + "</script>";

            TempData["notification"] = msg;
        }

        public void CargarDDL()
        {
            List<VehiculosDDL> listaV = new List<VehiculosDDL>();
            listaV.Insert(0, new VehiculosDDL { VehiculoId = 0, Info = "Seleccione un vehículo." });

            using (RentaCarrosEntities db = new RentaCarrosEntities())
            {
                foreach (var d in db.Vehiculos)
                {
                    VehiculosDDL aux = new VehiculosDDL();
                    aux.VehiculoId = d.VehiculoId;
                    aux.Info = "Marca: " + d.Marca + " Modelo: " + d.Modelo + " Matrícula: " + d.Matricula;

                    listaV.Add(aux);
                }
            }

            ViewBag.ListaVehiculos = listaV;
        }
    }
}

MVC_Proyecto_GRM/Views/Mantenimientos/Index.cshtml
@model List<MVC_Proyecto_GRM.Models.ViewModels.Mantenimientos.MantenimientosListar>
@{
    ViewBag.Title = "Listar Mantenimientos";
}

<div class="row p-md-2">
    <div class="card text-bg-dark">
        <img src="/Recursos/wp-1.jpg" class="card-img" alt="...">
        <div class="card-img-overlay text-center">
            <h1 class="card-title">@ViewBag.Title</h1>
            <p class="card-text">
                <small>
                    Para recordar como se manejan las acciones clic
                    @Html.ActionLink("aquí", "About", "Home", new { area = "" }, new { @class = "text-primary" }).
                </small>
            </p>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-2 m-md-2" style="text-align: right;">
        <a href="~/Mantenimientos/MantenimientoAgregar" class="btn btn-primary">Agregar Mantenimiento</a>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-striped table-bordered">

            <tr class="bg-warning text-center">
                <th style="width: 15%;">ID Mantenimiento</th>
                <th>Vehículo</th>
                <th>Nota</th>
                <th>Fecha</th>
                <th>Acciones</th>
            </tr>

            @foreach (var Elemento in Model)
            {
                <tr class="text-center">
                    <td>@Elemento.MantenimientoId</td>
                    <td>@Elemento.Vehiculo</td>
                    <td>@Elemento.Nota</td>
                    <td>@Elemento.Fecha</td>
                    <td>
                        <a class="btn btn-warning" href="~/Mantenimientos/MantenimientoEditar/@Elemento.MantenimientoId"><i class="fa-solid fa-pen-to-square"></i></a>
                        <a class="btn btn-danger" href="~/Mantenimientos/MantenimientoEliminar/@Elemento.MantenimientoId"><i class="fa-solid fa-trash"></i></a>
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

MVC_Proyecto_GRM/Views/Mantenimientos/MantenimientoAgregar.cshtml
@model MVC_Proyecto_GRM.Models.ViewModels.Mantenimientos.MantenimientoAgregar
@{
    ViewBag.Title = "Agregar un nuevo mantenimiento";
}

<div class="row p-md-2">
    <div class="card text-bg-dark">
        <img src="/Recursos/wp-1.jpg" class="card-img" alt="...">
        <div class="card-img-overlay text-center">
            <h1 class="card-title">@ViewBag.Title</h1>
        </div>
    </div>
</div>

@using (Html.BeginForm("MantenimientoAgregar", "Mantenimientos", FormMethod.Post))    // Metodo, Controller, Post Method
{
    <div class="row">
        <div class="col-md-6">
            <div>
                @Html.Label("Vehículo", null, new { @class = "lblTitulo" })
                @Html.DropDownListFor(d => d.VehiculoId, new SelectList(ViewBag.ListaVehiculos, "VehiculoId", "Info"), new { @class = "form-control" })
            </div>
            <div>
                @Html.LabelFor(d => d.Nota, null, new { @class = "lblTitulo" })
                @Html.TextBoxFor(d => d.Nota, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Nota, "", new { @class = "red" })
            </div>            
        </div>
        <div class="col-md-6">
            <div>
                @Html.LabelFor(d => d.Fecha, null, new { @class = "lblTitulo" })<br />
                @Html.EditorFor(d => d.Fecha, "", new { @class = "date" })
                @Html.ValidationMessageFor(d => d.Fecha, "", new { @class = "red" })
            </div>
            <div style="text-align: right;">
                <input value="Guardar" class="btn btn-success" type="submit" />
            </div>
        </div>
    </div>
}

MVC_Proyecto_GRM/Views/Mantenimientos/MantenimientoEditar.cshtml
@model MVC_Proyecto_GRM.Models.Mantenimientos

<div class="row p-md-2">
    <div class="card text-bg-dark">
        <img src="/Recursos/wp-1.jpg" class="card-img" alt="...">
        <div class="card-img-overlay text-center">
            <h2 class="card-title">Editando Mantenimiento</h2>
            <h4 class="card-body">>>> ID: @Html.ValueFor(d => d.MantenimientoId) <<<</h4>
        </div>
    </div>
</div>

@using (Html.BeginForm("MantenimientoEditar", "Mantenimientos", FormMethod.Post))    // Metodo, Controller, Post Method
{
    <div class="row">
        <div class="col-md-6">
            @Html.HiddenFor(d => d.MantenimientoId)
            @Html.HiddenFor(d => d.VehiculoId)
            <div>
                @Html.Label("Vehículo", null, new { @class = "lblTitulo" })
                @Html.DropDownListFor(d => d.VehiculoId, new SelectList(ViewBag.ListaVehiculos, "VehiculoId", "Info"), new { @class = "form-control", @disabled = "disabled" })
            </div>
            <div>
                @Html.LabelFor(d => d.Nota, null, new { @class = "lblTitulo" })
                @Html.TextBoxFor(d => d.Nota, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Nota, "", new { @class = "red" })
            </div>
        </div>
        <div class="col-md-6">
            <div>
                @Html.LabelFor(d => d.Fecha, null, new { @class = "lblTitulo" })<br />
                @Html.EditorFor(d => d.Fecha, "", new { @class = "date", htmlAttributes = new { ReadOnly = true, style = "background-color: #EEEEEE" } })
                @Html.ValidationMessageFor(d => d.Fecha, "", new { @class = "red" })
            </div>
            <div style="text-align: right;">
                <input value="Guardar" class="btn btn-success" type="submit" />
            </div>
        </div>
    </div>
}