MVC_Proyecto_GRM/Models/ViewModels/Vehiculos/VehiculoAgregar.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Xml.Linq;

namespace MVC_Proyecto_GRM.Models.ViewModels.Vehiculos
{
    public class VehiculoAgregar
    {
        public int VehiculoId { get; set; }

        [Required]  // Data validator
        [Display(Name = "Matrícula")]   // Manda el name de lo que falta
        public string Matricula { get; set; }

        [Required]  // Data validator
        [Display(Name = "Marca")]   // Manda el name de lo que falta
        public string Marca { get; set; }

        [Required]  // Data validator
        [Display(Name = "Modelo")]   // Manda el name de lo que falta
        public string Modelo { get; set; }

        [Required]  // Data validator
        [Display(Name = "Capacidad")]   // Manda el name de lo que falta
        public int Capacidad { get; set; }

        [Required]  // Data validator
        [Display(Name = "Kilometraje")]   // Manda el name de lo que falta
        public float Kilometraje { get; set; }
    }
}

MVC_Proyecto_GRM/Models/ViewModels/Vehiculos/VehiculosListar.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC_Proyecto_GRM.Models.ViewModels.Vehiculos
{
    public class VehiculosListar
    {
        public int VehiculoId { get; set; }
        public string Matricula { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public int Capacidad { get; set; }
        public float Kilometraje { get; set; }
    }
}

MVC_Proyecto_GRM/Controllers/VehiculosController.cs
using MVC_Proyecto_GRM.Models.ViewModels.Direcciones;
using MVC_Proyecto_GRM.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_Proyecto_GRM.Models.ViewModels.Vehiculos;
using static MVC_Proyecto_GRM.Models.Enum;

namespace MVC_Proyecto_GRM.Controllers
{
    public class VehiculosController : Controller
    {        
        // GET: Vehiculos
        public ActionResult Index()
        {
            List<VehiculosListar> lista = new List<VehiculosListar>();

            // Entity framework
            using (RentaCarrosEntities db = new RentaCarrosEntities())
            {
                // LinQ
                lista = (from vehiculo in db.Vehiculos
                         select new VehiculosListar
                         {
                             VehiculoId = vehiculo.VehiculoId,
                             Matricula = vehiculo.Matricula,
                             Marca = vehiculo.Marca,
                             Modelo = vehiculo.Modelo,
                             Capacidad = vehiculo.Capacidad,
                             Kilometraje = (float)vehiculo.Kilometraje,
                         }).ToList();
            }

            return View(lista);
        }

        public ActionResult VehiculoAgregar()
        {
            return View();
        }

        [HttpPost] // Data validator
        public ActionResult VehiculoAgregar(VehiculoAgregar model)
        {
            try
            {
                // Validar si modelo es correcto
                if (ModelState.IsValid)
                {
                    using (RentaCarrosEntities db = new RentaCarrosEntities())
                    {
                        foreach (var item in db.Vehiculos)
                        {
                            if (item.Matricula == model.Matricula)
                            {
                                Alert("Ya existe un vehículo con la misma matrícula.", NoticationType.error);
                                return View(model);
                            }
                        }

                        var vehiculo = new Vehiculos();

                        vehiculo.Matricula = model.Matricula;
                        vehiculo.Marca = model.Marca;
                        vehiculo.Modelo = model.Modelo;
                        vehiculo.Capacidad = model.Capacidad;
                        vehiculo.Kilometraje = model.Kilometraje;

                        // Se agrega el nuevo camion
                        db.Vehiculos.Add(vehiculo);
                        db.SaveChanges();

                        Alert("El Vehículo ha sido agregado", NoticationType.success);

                    }
                    // Redirecciona a la lista de camiones (Controller)
                    return Redirect("~/Vehiculos");
                }
                Alert("Verificar la información", NoticationType.warning);
                return View(model);
            }
            catch (Exception ex)
            {
                Alert("Error: " + ex.Message, NoticationType.error);
                return View(model);
            }
        }

        public ActionResult VehiculoEditar(int id)
        {
            Vehiculos vehiculo = new Vehiculos();

            using (RentaCarrosEntities db = new RentaCarrosEntities())
            {
                //camion = db.Camiones.Where(x => x.CamionId == camionId).OrderBy(x => x.Matricula).FirstOrDefault();
                vehiculo = db.Vehiculos.Where(x => x.VehiculoId == id).FirstOrDefault();
            }

            return View(vehiculo);
        }

        [HttpPost]
        public ActionResult VehiculoEditar(Vehiculos model)
        {
            try
            {
                // Validar si modelo es correcto
                if (ModelState.IsValid)
                {
                    using (RentaCarrosEntities db = new RentaCarrosEntities())
                    {
                        var vehiculo = new Vehiculos();

                        vehiculo.VehiculoId = model.VehiculoId;
                        vehiculo.Matricula = model.Matricula;
                        vehiculo.Marca = model.Marca;
                        vehiculo.Modelo = model.Modelo;
                        vehiculo.Capacidad = model.Capacidad;
                        vehiculo.Kilometraje = model.Kilometraje;

                        // Se agrega el nuevo camion                        
                        db.Entry(vehiculo).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();

                        Alert("El Vehículo ha sido actualizado", NoticationType.success);
                    }
                    // Redirecciona a la lista de camiones
                    return Redirect("~/Vehiculos");
                }
                Alert("El kilometraje no puede estar vacío y debe ser mayor o igual al que tenía", NoticationType.warning);
                return View(model);
            }
            catch (Exception ex)
            {
                Alert("Error: " + ex.Message, NoticationType.error);
                return View(model);
                //throw new Exception(ex.Message);
            }
        }

        [HttpGet]
        public ActionResult VehiculoEliminar(int id)
        {
            Vehiculos vehiculo = new Vehiculos();
            try
            {
                using (RentaCarrosEntities db = new RentaCarrosEntities())
                {
                    vehiculo = db.Vehiculos.Where(x => x.VehiculoId == id).FirstOrDefault();
                    db.Vehiculos.Remove(vehiculo);
                    db.SaveChanges();
                }
                Alert("Vehículo Eliminado con éxito.", NoticationType.success);
                return Redirect("~/Vehiculos");
            }
            catch (Exception ex)
            {
                Alert("El Vehículo no puede ser eliminado porque posee mantenimiento(s) o renta(s).", NoticationType.error);
                return Redirect("~/Vehiculos");
            }
        }

        public void Alert(string message, NoticationType noticationType)
        {
            var msg = "<script language='javascript'>Swal.fire('" + noticationType.ToString().ToUpper() + "', '" + message +
                "','" + noticationType + "')" + "</script>";

            TempData["notification"] = msg;
        }
    }
}

MVC_Proyecto_GRM/Views/Vehiculos/Index.cshtml
@model List<MVC_Proyecto_GRM.Models.ViewModels.Vehiculos.VehiculosListar>
@{
    ViewBag.Title = "Listar Vehículos";
}

<div class="row p-md-2">
    <div class="card text-bg-dark">
        <img src="/Recursos/wp-1.jpg" class="card-img" alt="...">
        <div class="card-img-overlay text-center">
            <h1 class="card-title">@ViewBag.Title</h1>
            <p class="card-text">
                <small>
                    Para recordar como se manejan las acciones clic
                    @Html.ActionLink("aquí", "About", "Home", new { area = "" }, new { @class = "text-primary" }).
                </small>
            </p>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-2 m-md-2" style="text-align: right;">
        <a href="~/Vehiculos/VehiculoAgregar" class="btn btn-primary">Agregar Vehículo</a>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-striped table-bordered">

            <tr class="bg-warning text-center">
                <th style="width: 15%;">ID Vehículo</th>
                <th>Matrícula</th>
                <th>Marca</th>
                <th>Modelo</th>
                <th>Capacidad</th>
                <th>Kilometraje</th>
                <th>Acciones</th>
            </tr>

            @foreach (var Elemento in Model)
            {
                <tr class="text-center">
                    <td>@Elemento.VehiculoId</td>
                    <td>@Elemento.Matricula</td>
                    <td>@Elemento.Marca</td>
                    <td>@Elemento.Modelo</td>
                    <td>@Elemento.Capacidad</td>
                    <td>@Elemento.Kilometraje</td>
                    <td>
                        <a class="btn btn-warning" href="~/Vehiculos/VehiculoEditar/@Elemento.VehiculoId"><i class="fa-solid fa-pen-to-square"></i></a>
                        <a class="btn btn-danger" href="~/Vehiculos/VehiculoEliminar/@Elemento.VehiculoId"><i class="fa-solid fa-trash"></i></a>
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

MVC_Proyecto_GRM/Views/Vehiculos/VehiculoAgregar.cshtml
@model MVC_Proyecto_GRM.Models.ViewModels.Vehiculos.VehiculoAgregar
@{
    ViewBag.Title = "Agregar un nuevo vehículo";
}

<div class="row p-md-2">
    <div class="card text-bg-dark">
        <img src="/Recursos/wp-1.jpg" class="card-img" alt="...">
        <div class="card-img-overlay text-center">
            <h1 class="card-title">@ViewBag.Title</h1>            
        </div>
    </div>
</div>

@using (Html.BeginForm("VehiculoAgregar", "Vehiculos", FormMethod.Post))    // Metodo, Controller, Post Method
{
    <div class="row">
        <div class="col-md-6">
            <div>
                @Html.LabelFor(d => d.Matricula, null, new { @class = "lblTitulo" })
                @Html.TextBoxFor(d => d.Matricula, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Matricula, "", new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.Marca, null, new { @class = "lblTitulo" })
                @Html.TextBoxFor(d => d.Marca, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Marca, "", new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.Modelo, null, new { @class = "lblTitulo" })
                @Html.TextBoxFor(d => d.Modelo, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Modelo, "", new { @class = "red" })
            </div>
        </div>

        <div class="col-md-6">            
            <div>
                @Html.LabelFor(d => d.Capacidad, null, new { @class = "lblTitulo" })
                @Html.TextBoxFor(d => d.Capacidad, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Capacidad, "", new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.Kilometraje, null, new { @class = "lblTitulo" })
                @Html.TextBoxFor(d => d.Kilometraje, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Kilometraje, "", new { @class = "red" })
            </div>
            <div style="text-align: right;">
                <input value="Guardar" class="btn btn-success" type="submit" />
            </div>
        </div>
    </div>
}

MVC_Proyecto_GRM/Views/Vehiculos/VehiculoEditar.cshtml
@model MVC_Proyecto_GRM.Models.Vehiculos

<div class="row p-md-2">
    <div class="card text-bg-dark">
        <img src="/Recursos/wp-1.jpg" class="card-img" alt="...">
        <div class="card-img-overlay text-center">
            <h2 class="card-title">Editando vehículo</h2>
            <h4 class="card-body">>>> ID: @Html.ValueFor(d => d.VehiculoId) <<<</h4>
        </div>
    </div>
</div>

@using (Html.BeginForm("VehiculoEditar", "Vehiculos", FormMethod.Post))    // Metodo, Controller, Post Method
{
    <div class="row">
        <div class="col-md-6">
            @Html.HiddenFor(d => d.VehiculoId)
            <div>
                @Html.LabelFor(d => d.Matricula, null, new { @class = "lblTitulo" })
                @Html.TextBoxFor(d => d.Matricula, "", new { @class = "form-control", @readonly = "readonly" })
                @Html.ValidationMessageFor(d => d.Matricula, "", new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.Marca, null, new { @class = "lblTitulo" })
                @Html.TextBoxFor(d => d.Marca, "", new { @class = "form-control", @readonly = "readonly" })
                @Html.ValidationMessageFor(d => d.Marca, "", new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.Modelo, null, new { @class = "lblTitulo" })
                @Html.TextBoxFor(d => d.Modelo, "", new { @class = "form-control", @readonly = "readonly" })
                @Html.ValidationMessageFor(d => d.Modelo, "", new { @class = "red" })
            </div>            
        </div>
        <div class="col-md-6">
            <div>
                @Html.LabelFor(d => d.Capacidad, null, new { @class = "lblTitulo" })
                @Html.TextBoxFor(d => d.Capacidad, "", new { @class = "form-control", @readonly = "readonly" })
                @Html.ValidationMessageFor(d => d.Capacidad, "", new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.Kilometraje, null, new { @class = "lblTitulo" })
                @Html.TextBoxFor(d => d.Kilometraje, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Kilometraje, "", new { @class = "red" })
            </div>
            <div style="text-align: right;">
                <input value="Guardar" class="btn btn-success" type="submit" />
            </div>
        </div>
    </div>
}